# Generated by Django 4.2.1 on 2023-07-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meal_plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe",
                to="meal_plans.meal",
            ),
        ),
    ]
