# Generated by Django 4.2.1 on 2023-07-09 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal_plans", "0002_alter_recipe_meal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"verbose_name_plural": "meals"},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name_plural": "recipes"},
        ),
    ]
