# Generated by Django 4.2.1 on 2023-07-11 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal_plans", "0003_alter_meal_options_alter_recipe_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={},
        ),
    ]
